# Gradle & IDE
org.gradle.jvmargs=-Xmx2G

# Project
mod_version=0.7.1
maven_group=me.adda
archives_base_name=efallingtrees

# Minecraft & Mappings
minecraft_version=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_loader_version=0.16.14
fabric_api_version=0.119.4+1.21.4

# Forge
forge_version=54.1.16

# NeoForge
neoforge_version=21.4.157

# Common Dependencies
cloth_config_version=17.0.144
cloth_config_neoforge_version=17.0.144

# Optional Dependencies
jade_minecraft_version=1.21.4
jade_version=17.2.2
modmenu_version=13.0.4
