# Gradle & IDE
org.gradle.jvmargs=-Xmx2G

# Project
mod_version=0.7.1
maven_group=me.adda
archives_base_name=efallingtrees

# Minecraft & Mappings
minecraft_version=1.21.7
parchment_version=2025.07.18

# Fabric
fabric_loader_version=0.16.14
fabric_api_version=0.128.2+1.21.7

# Forge
forge_version=57.0.3

# NeoForge
neoforge_version=21.7.25-beta

# Common Dependencies
cloth_config_version=19.0.147
cloth_config_neoforge_version=19.0.147

# Optional Dependencies
jade_minecraft_version=1.21.7
jade_version=19.3.2
modmenu_version=15.0.2
